-- Enable configured LSPs in lsp/*.lua
vim.lsp.enable("bashls")
vim.lsp.enable("clangd")
vim.lsp.enable("hls")
vim.lsp.enable("hyprls")
vim.lsp.enable("jsonls")
vim.lsp.enable("matlabls")
vim.lsp.enable("nixd")
vim.lsp.enable("qmlls")
vim.lsp.enable("ruff")
vim.lsp.enable("rust-analyzer")
vim.lsp.enable("stylua")
vim.lsp.enable("lua_ls")
vim.lsp.enable("texlab")
vim.lsp.enable("tinymist")
vim.lsp.enable("zls")
